### ISSUE TITLE
Add a random button 

### ISSUE THREAD

**Issue by xSk1p** [ranrib/wolt-explorer#37]
We get hard times choosing what to eat.

**Comment by ranrib** [comment]
Would you like to have a button that just opens a restaurant? How about implementing it yourself? :)

**Comment by xSk1p** [comment]
My React is a bit rusty, but I'll try :)


‫בתאריך יום א׳, 24 ביולי 2022 ב-11:58 מאת ‪Ran Ribenzaft‬‏ <‪
***@***.***‬‏>:‬

**Comment by xSk1p** [comment]
PR: https://github.com/ranrib/wolt-explorer/pull/38
